spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/finapp}
    username: ${DB_USERNAME:finapp}
    password: ${DB_PASSWORD:finapp}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration
server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
