spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/finapp}
    username: ${SPRING_DATASOURCE_USERNAME:finapp}
    password: ${SPRING_DATASOURCE_PASSWORD:finapp}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
  main:
    allow-bean-definition-overriding: true

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.springframework.security: DEBUG
# =========================
# Development profile
# =========================
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/financial_app_dev
    username: finapp
    password: finapp
  jpa:
    show-sql: true
  flyway:
    enabled: false
  main:
    banner-mode: console

server:
  port: 8080
logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
# =========================
# Production profile
# =========================
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: false
  flyway:
    enabled: true
server:
  port: ${PORT:8080}
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: ERROR